services:
  cilent:
    build: client
    image: natapon/image-frontend:lastest
    ports:
      - "8081:80"
    container_name: my-frontend
  server:
    build: server
    image: natapon/image-server:lastest
    ports:
      - "8085:80"
    container_name: my-server